"""Proof that the worker is running the production models, and nothing else.

Three checks, in the order a run meets them:

1. **Checksum before unpickling.** Every artifact is hashed and compared with
   ``model_manifest.json`` before ``joblib.load`` touches it. A file with the
   right name and the wrong contents — a retrained model copied over the old
   one, a truncated download, a different version renamed — never gets loaded.
2. **Metadata and libraries.** The bundle must name the model version, pathogen
   and feature version the manifest records, and the container's scikit-learn,
   NumPy and RDKit must be the versions the model was trained with. A pickled
   estimator is only guaranteed to behave identically under the library that
   fitted it, and the fingerprint only under the RDKit that defined it.
3. **Known answers.** Before anything new is scored, the worker recomputes the
   published predictions for five named medicines — through the same
   fingerprint function and the same model call a new medicine goes through —
   and compares them with the manifest and with the live database. One number
   outside 1e-9 stops the run.

Every failure raises :class:`ModelIntegrityError` with the reason. Nothing is
ever substituted: there is no fallback model and no default prediction.

The manifest is generated by ``scripts/build_worker_manifest.py``; nothing in it
is typed by hand.

Run on its own (the image build does this, so a wrong artifact fails the build):

    python -m src.updater.integrity --models-dir models
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
from typing import Any, Callable

import numpy as np

MANIFEST_PATH = Path(__file__).with_name("model_manifest.json")


class ModelIntegrityError(RuntimeError):
    """The loaded models are not, provably, the production models."""


def load_manifest(path: Path = MANIFEST_PATH) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ModelIntegrityError(
            f"model manifest missing at {path}; the image cannot prove which models it carries"
        ) from exc


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def manifest_entry(manifest: dict[str, Any], pathogen: str, model_version: str) -> dict[str, Any]:
    entry = manifest["models"].get(pathogen)
    if entry is None:
        raise ModelIntegrityError(f"the manifest pins no model for {pathogen}")
    if entry["model_version"] != model_version:
        raise ModelIntegrityError(
            f"{pathogen}: the registry names {model_version} but this image pins "
            f"{entry['model_version']}. Regenerate the manifest and rebuild the image "
            "for a newly promoted model."
        )
    return entry


def verify_artifact(path: Path, entry: dict[str, Any]) -> None:
    """Size and SHA-256 must match, checked before the file is unpickled."""
    if not path.is_file():
        raise ModelIntegrityError(f"{entry['model_version']}: artifact {path} is missing")
    size = path.stat().st_size
    if size != entry["bytes"]:
        raise ModelIntegrityError(
            f"{entry['model_version']}: {path.name} is {size} bytes, expected "
            f"{entry['bytes']} — the file is not the production artifact"
        )
    actual = sha256_of(path)
    if actual != entry["sha256"]:
        raise ModelIntegrityError(
            f"{entry['model_version']}: {path.name} has SHA-256 {actual}, expected "
            f"{entry['sha256']} — the file is not the production artifact"
        )


def verify_bundle(bundle: Any, entry: dict[str, Any], pathogen: str) -> None:
    """The unpickled bundle must describe itself as the pinned model."""
    if not isinstance(bundle, dict) or "model" not in bundle:
        raise ModelIntegrityError(f"{entry['model_version']}: not a model bundle")
    for key, expected in (
        ("model_version", entry["model_version"]),
        ("pathogen_key", pathogen),
        ("feature_version", entry["feature_version"]),
        ("n_features", entry["n_features"]),
    ):
        if bundle.get(key) != expected:
            raise ModelIntegrityError(
                f"{entry['model_version']}: bundle {key} is {bundle.get(key)!r}, "
                f"expected {expected!r}"
            )
    if not hasattr(bundle["model"], "predict_proba"):
        raise ModelIntegrityError(f"{entry['model_version']}: estimator cannot predict_proba")


def _version_tuple(version: str) -> tuple[int, ...]:
    # RDKit reports "2026.03.6" at run time and installs as "2026.3.6".
    return tuple(int(part) for part in version.split(".") if part.isdigit())


def installed_versions() -> dict[str, str]:
    from rdkit import rdBase

    return {
        "scikit-learn": metadata.version("scikit-learn"),
        "numpy": np.__version__,
        "rdkit": rdBase.rdkitVersion,
    }


def verify_libraries(entry: dict[str, Any], installed: dict[str, str] | None = None) -> None:
    installed = installed or installed_versions()
    for library, trained in entry["library_versions"].items():
        if _version_tuple(installed[library]) != _version_tuple(trained):
            raise ModelIntegrityError(
                f"{entry['model_version']} was trained with {library} {trained}; this "
                f"container has {installed[library]}. Predictions are only reproducible "
                "under the library that fitted the model."
            )


@dataclass(frozen=True)
class KnownAnswerResult:
    generic_name: str
    molecule_id: str
    pathogen: str
    model_version: str
    manifest: float
    published: float | None
    recomputed: float

    @property
    def worst_difference(self) -> float:
        diffs = [abs(self.recomputed - self.manifest)]
        if self.published is not None:
            diffs.append(abs(self.recomputed - self.published))
        return max(diffs)


def run_known_answers(
    loaded: dict[str, Any],
    manifest: dict[str, Any],
    featurise: Callable[[str], np.ndarray],
    published: dict[tuple[str, str, str], float] | None = None,
) -> list[KnownAnswerResult]:
    """Recompute every known answer and fail on the first that drifts.

    ``featurise`` must be the function the worker uses for a new medicine, so
    that this checks the path new medicines actually take. ``published`` is the
    live database's probability per (molecule, pathogen, model version); when
    given, a known answer must match it as well as the manifest, which proves the
    container reproduces what the website is showing.
    """
    tolerance = float(manifest["tolerance"])
    results: list[KnownAnswerResult] = []

    for case in manifest["known_answers"]:
        features = featurise(case["canonical_smiles"])
        for pathogen, model in sorted(loaded.items()):
            version = model.meta.model_version
            recomputed = float(model.predict(features)[0])
            live = None
            if published is not None:
                live = published.get((case["molecule_id"], pathogen, version))
                if live is None:
                    raise ModelIntegrityError(
                        f"known answer {case['generic_name']} / {pathogen} has no published "
                        f"{version} prediction to compare with"
                    )
            result = KnownAnswerResult(
                generic_name=case["generic_name"],
                molecule_id=case["molecule_id"],
                pathogen=pathogen,
                model_version=version,
                manifest=float(case["probabilities"][pathogen]),
                published=live,
                recomputed=recomputed,
            )
            if result.worst_difference > tolerance:
                raise ModelIntegrityError(
                    f"known answer failed: {case['generic_name']} / {version} recomputed "
                    f"{recomputed!r}, manifest {result.manifest!r}, published {live!r}"
                )
            results.append(result)
    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Verify the pinned model artifacts.")
    parser.add_argument("--models-dir", type=Path, required=True)
    args = parser.parse_args(argv)

    manifest = load_manifest()
    try:
        for pathogen, entry in sorted(manifest["models"].items()):
            verify_artifact(args.models_dir / entry["file"], entry)
            verify_libraries(entry)
            print(f"ok  {entry['model_version']:<20} {entry['sha256']}  {pathogen}")
    except ModelIntegrityError as exc:
        print(f"MODEL INTEGRITY FAILURE: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
